export const SET_MACHINES_LOADING = 'SET_MACHINES_LOADING';
export const GET_MACHINES = 'GET_MACHINES';
export const GET_MACHINE_DETAILS = 'GET_MACHINE_DETAILS';
export const UPDATE_MACHINE_DETAILS = 'UPDATE_MACHINE_DETAILS';
